Vagrant.configure("2") do |config|

  config.vm.define "hasabirS" do |node|
    node.vm.box = "generic/alpine318"
    node.vm.box_version = "4.3.12"
    node.vm.hostname = "hasabirS"
    node.vm.network "private_network", ip: "192.168.56.110"
    node.vm.synced_folder "./apps", "/vagrant"

    node.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
      vb.name = "hasabirS"
    end

    node.vm.provision "shell", path: "script.sh"
  end
end
