
Vagrant.configure("2") do |config|
  servers = [
    {
      :name => "hasabirS",
      :ip => "192.168.56.110",
      :hostname => "hasabirS",
      :box => "generic/alpine318",
      :box_version => "4.3.12",
      :type => "server"
    },
    {
      :name => "hasabirSW",
      :hostname => "hasabirSW",
      :ip => "192.168.56.111",
      :box => "generic/alpine318",
      :box_version => "4.3.12",
      :type => "agent"
    }
  ]

  servers.each do |machine|
    config.vm.define machine[:name] do |node|
      node.vm.box = machine[:box]
      node.vm.box_version = machine[:box_version]
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]
      node.vm.synced_folder ".", "/vagrant"

      node.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
        vb.cpus = 1
        vb.name = machine[:name]
      end

      node.vm.provision "shell", path: "script.sh", args: [machine[:type]]

    end
  end
end



# Setup SSH key-based authentication

# node.vm.provision "file" :shell, ""
# node.vm.provision "shell", inline: <<-SHELL
#   mkdir -p /home/vagrant/.ssh
#   cp /vagrant/id_rsa.pub /home/vagrant/.ssh/authorized_keys
#   chmod 600 /home/vagrant/.ssh/authorized_keys
#   chown -R vagrant:vagrant /home/vagrant/.ssh
# SHELL





# Vagrant.configure("2") do |config|
#   servers = [
#     {
#       :name => "test",
#       :ip => "192.168.56.110",
#       :hostname => "test",
#       :box => "generic/alpine318",
#       :box_version => "4.3.12",
#     },

#   ]

#   servers.each do |machine|
#     config.vm.define machine[:name] do |node|
#       node.vm.box = machine[:box]
#       node.vm.box_version = machine[:box_version]
#       node.vm.hostname = machine[:hostname]
#       node.vm.network "private_network", ip: machine[:ip]
#       node.vm.synced_folder ".", "/vagrant"

#       node.vm.provider "virtualbox" do |vb|
#         vb.memory = "512"
#         vb.cpus = 1
#         vb.name = machine[:name]
#       end

#     end
#   end
# end
  
  
  #     # node.provision :shell, path: "script.sh"
  #     # node.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
  
  
  #   # config.vm.box = "generic/alpine318"
  #   # config.vm.box_version = "4.3.12"
  
  
  
  
  #   # config.vm.hostname = "alpineS"
  #   # config.vm.provider "virtualbox" do |vb|
  #   #   vb.memory = "1024"
  #   #   vb.cpus = 1
  #   #   vb.name = "hasabir"
  #   # end
  
  #   # config.vm.provision :shell, path: "script.sh"
  #   # config.vm.network "private_network", ip: "192.168.56.110"
  #   # config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
  #   # config.vm.synced_folder ".", "/vagrant"
  

  